# This is a basic workflow to help you get started with Actions

name: main

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '59 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install R Package (multi-line script)
    - uses: r-lib/actions/setup-r@v1
    - name: Install Package Dependencies
      run: |-
        Rscript -e "install.packages('remotes')"
        Rscript -e "remotes::install_github('gadenbuie/tweetrmd')"
        Rscript -e "remotes::install_github('rstudio/webshot2')"
        Rscript -e "install.packages('rtweet')"  

    # Generate Twitter Image
    - name: Generate Twitter Image
      env:
        ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      run: |-
        Rscript -e "source('script.R')"
